name: GCP Infrastructure Provisioning

on:
  # trigger this manually from the GitHub UI Actions tab
  workflow_dispatch: 
  # Optional: Runs only when changes are made inside the terraform directory
  push:
    paths:
      - 'terraform/nonprod/**'
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  terraform-provision:
    name: Run Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Plan
        run: |
          cd terraform
          terraform init
          terraform plan -var="project_id=${{ env.GCP_PROJECT_ID }}"